<div class="footer">
    <div class="footer-col1">
        <div class="footer-col1-item1">
            <?php
            echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('browse-basecamp')

                    ->toHtml();
            ?>
        </div>
        <div class="footer-col1-item2">
            <?php
                echo $block->getLayout()

                        ->createBlock('Magento\Cms\Block\Block')

                        ->setBlockId('stay-connected')

                        ->toHtml();
                ?>
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('link-footer-fb-tw-mail')->toHtml(); ?>
        </div>
    </div>
    <div class="footer-col2">
        <div class="footer-col2-item1">
            <?php
            echo $block->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('my-account')
                    ->toHtml();
            ?>
        </div>
        <div class="footer-col2-item2">
            <?php
            echo $block->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('we-accept')
                    ->toHtml();
            ?>
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('link-card-footer')->toHtml(); ?>
        </div>
    </div>
    <div class="footer-col3">
        <div class="footer-col3-item1">
            <?php
            echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('terms-and-conditions')

                    ->toHtml();
            ?>
        </div>
        <div class="footer-col3-item2">
            <?php
            echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('footer-logo')

                    ->toHtml();
            ?>
        </div>
    </div>
    <div class="footer-col4">
        <div class="footer-col4-item1">
            <?php
            echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('we-are-located-at')

                    ->toHtml();
            ?>
        </div>
        <div class="footer-col4-item2">
            <?php
            echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('footer-address1')

                    ->toHtml();
            ?>
        </div>
        <hr>
        <div class="footer-col4-item3">
            <?php
            echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('kilkenny-address')

                    ->toHtml();
            ?>
        </div>
        <div class="footer-col4-item4">
            <?php
            echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('footer-address')

                    ->toHtml();
            ?>
        </div>
    </div>
</div>