<ul class="list-ads-top">
    <?php
    for ($i = 1; $i <= 2; $i++) {
        ?>
        <li class="list-item-top">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ads-' . $i)->toHtml(); ?>
        </li>
        <?php
    }
    ?>
</ul>
<!-- <script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".list-ads-top").slick({
                dots: false,
                infinite: true,
                speed: 300,
                slidesToShow: 2,
                slidesToScroll: 1
            });
        });
    });
</script> -->