<ul class="list-ads-bottom">
    <?php
    for ($i = 1; $i <= 3; $i++) {
        ?>
        <li class="list-item-bottom">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ads-two-' . $i)->toHtml(); ?>
        </li>
        <?php
    }
    ?>
</ul>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".list-ads-bottom").slick({
                dots: false,
                infinite: true,
                speed: 300,
                slidesToShow: 3,
                slidesToScroll: 1
            });
        });
    });
</script>
