<ul class="list-category">
    <?php for($i=1;$i<=5;$i++){ ?>
        <div class="category-populor-item">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category-popular-' . $i)->toHtml(); ?>
            <span>
                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popular-text-' . $i)->toHtml(); ?>
            </span>
        </div>
    <?php } ?>
</ul>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".list-category").slick({
                dots: false,
                infinite: true,
                speed: 300,
                slidesToShow: 5,
                slidesToScroll: 1,
                responsive: [
                    {
                        breakpoint: 1440,
                        settings: {
                            arrows: false,
                            slidesToShow: 5
                        }
                    },
                    {
                        breakpoint: 1024,
                        settings: {
                            arrows: false,
                            slidesToShow: 4
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            arrows: false,
                            slidesToShow: 3
                        }
                    },
                    {
                        breakpoint: 480,
                        settings: {
                            arrows: false,
                            slidesToShow: 2
                        }
                    }
                ]
            });
        });
    });
</script>