<div class="sponsor-content">
    <ul class="list-sponsor">
        <?php
            for($i = 1;$i<=8;$i++){
        ?>
            <li class="list-sponsor-item">
                    <div class="sponsor-image">
                        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sponsor-' . $i)->toHtml(); ?>
                    </div>
            </li>
        <?php } ?>
    </ul>
</div>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".list-sponsor").slick({
                dots: false,
                infinite: true,
                speed: 300,
                slidesToShow: 8,
                slidesToScroll: 1,
                centerPadding: '0px',
            });
        });
    });
</script>